# Generated by Django 5.1.1 on 2024-10-10 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1000)]),
        ),
    ]
